import * as React from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

import { useRouter, withRouter } from 'next/router'



const Home: NextPage = () => {
  const [text, setText] = React.useState("");
  const router = useRouter();

  const handleClick = (e:any) => {
    e.preventDefault()
    router.push('/profile/' + text)
  }

  const handleChange = (e:any) =>{
    setText(e.target.value);
  }


  return (

    <div className={styles.main}>
      <Head>
        <title>Create Bean App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>

        <div className={styles.container}>
          <div className={styles.typewriter}>
            <h1>Who are you looking for?</h1>
            <form onSubmit={handleClick}>
              <input
                onChange={(text) => handleChange(text)}>
              </input>
            </form>
          </div>
        </div>

        {/* <div className={styles.container}>
            <Link href="/profile/Vi">
              <Image src="https://cdn.imgbin.com/23/1/24/imgbin-lima-bean-common-bean-green-bean-cartoon-coffee-beans-green-bean-character-illustration-0dTGDxwUUTN8xd13ZbwnJCGCb.jpg" width={200} height={200} />
            </Link>
          </div>
          <div className={styles.container}>
            <Link href="/profile/Joe">
              <Image src="https://image.spreadshirtmedia.net/image-server/v1/mp/products/T1459A839MPA4459PT28D15720325FS7770/views/1,width=550,height=550,appearanceId=839,backgroundColor=F2F2F2/super-papi-sticker.jpg" width={200} height={200} />
            </Link>
          </div> */}
      </main>
    </div>


  )
}

export default Home
