import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Bean App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Hello Bean
        </h1>
        <Image src="https://img.btdmp.com/10327/10327979/products/0x110_x2@16540809379c306bd2bf.jpeg"  width={200} height={200}/>
      </main>
    </div>
  )
}

export default Home
